# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-18 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('description', models.TextField(max_length=200, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('img', models.ImageField(help_text='270x270px', upload_to='projects/', verbose_name='\u041f\u0440\u0435\u0432\u044c\u044e')),
                ('site_link', models.URLField(blank=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u0430\u0439\u0442')),
                ('github_link', models.URLField(blank=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 github')),
            ],
            options={
                'db_table': 'Projects',
                'verbose_name': '\u041f\u0440\u043e\u0435\u043a\u0442',
                'verbose_name_plural': '\u041f\u0440\u043e\u0435\u043a\u0442\u044b',
            },
        ),
    ]
